# Generated by Django 3.0.5 on 2020-04-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stacionet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stacion_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Linjat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linja_name', models.CharField(max_length=100)),
                ('stacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacionet.Stacionet')),
            ],
        ),
    ]
